### PR TITLE
Migration to Extensions (Dart 2.6)

### PR DESCRIPTION
**Pull request by passsy**
Dart 2.6 introduces [extension methods](https://github.com/dart-lang/language/issues/41#issuecomment-539251446). The aim of this project was always to provide tons of extensions.

This PR enables migrates the old extension mixins to real extensions. Nothing else. No further APIs or internal extension usage

### CODE REVIEW

**Comment by shinayser** [comment]
Will be the "KtMap" "KtList" classes still be needed?
Why not just provide extensions over the language's standard classes like List and Map?

**Comment by passsy** [comment]
Immutable Kt collections fill a gap in the Dart SDK. Dart collections only have mutable ones. Thus `KtList`, `KtMap` and `KtSet` are still usefull even with the introduction of extension methods.

I'm thinking about how ktdart could provide extensions for Dart collections as well. I'm still experimenting and haven't come to a real answer what's the best way to introduce them.

For now, you can convert every Dart collection to a Kt collection using the `kt` extension property.

```dart
List<String> dartList = ["plain", "dart", "list"]; // mutable 😒 
KtList<String> ktList = ["plain", "dart", "list"].kt; // immutable 👍 
```

But it doesn't work well for mutable collections because `kt` creates a copy which might be unexpected

```dart
  final beatles = {"John", "Paul", "George", "Ringo"};
  beatles.kt.toMutableSet().remove("Paul");
  print(beatles); // {John, Paul, George, Ringo} 
```

Usually in Dart, `List` operators like `map` or `where` return an `Iterable`. This makes them work like `Sequences` in kotlin. They are very efficient and don't create copies but views of the data. The downside is that you have to use `.toList(growable: false)` every time you operate on a `List` and you want to preserve the type. That's super annoying.

ktdart `KtList` operators create copies and return a `KtList`. No `toList()` is required but every operator copies data which might not be ideal.

Kotlin solves this my allowing users to explicitly specify if users what to use Sequences (`asSequence()`) or copy by default.

I'm unsure which route to go for the Dart SDK collection extensions. Follow the Dart SDK design decisions I'm not happy with (sequences and mutability by default), or to provide better methods which behave differently from SDK methods which could cause confusion.

Another solution is to stick with what ktdart is right now: Separate collections and a way to interop with the Dart SDK. 
Then create the extensions for the Dart SDK in the [`collections`](https://pub.dev/packages/collection) package. This would make sure the methods feel darty.

**Comment by shinayser** [comment]
> Immutable Kt collections fill a gap in the Dart SDK. Dart collections only have mutable ones. Thus `KtList`, `KtMap` and `KtSet` are still usefull even with the introduction of extension methods.
> 
> I'm thinking about how ktdart could provide extensions for Dart collections as well. I'm still experimenting and haven't come to a real answer what's the best way to introduce them.
> 
> For now, you can convert every Dart collection to a Kt collection using the `kt` extension property.
> 
> ```dart
> List<String> dartList = ["plain", "dart", "list"]; // mutable 😒 
> KtList<String> ktList = ["plain", "dart", "list"].kt; // immutable 👍 
> ```
> 
> But it doesn't work well for mutable collections because `kt` creates a copy which might be unexpected
> 
> ```dart
>   final beatles = {"John", "Paul", "George", "Ringo"};
>   beatles.kt.toMutableSet().remove("Paul");
>   print(beatles); // {John, Paul, George, Ringo} 
> ```
> 
> Usually in Dart, `List` operators like `map` or `where` return an `Iterable`. This makes them work like `Sequences` in kotlin. They are very efficient and don't create copies but views of the data. The downside is that you have to use `.toList(growable: false)` every time you operate on a `List` and you want to preserve the type. That's super annoying.
> 
> ktdart `KtList` operators create copies and return a `KtList`. No `toList()` is required but every operator copies data which might not be ideal.
> 
> Kotlin solves this my allowing users to explicitly specify if users what to use Sequences (`asSequence()`) or copy by default.
> 
> I'm unsure which route to go for the Dart SDK collection extensions. Follow the Dart SDK design decisions I'm not happy with (sequences and mutability by default), or to provide better methods which behave differently from SDK methods which could cause confusion.
> 
> Another solution is to stick with what ktdart is right now: Separate collections and a way to interop with the Dart SDK.
> Then create the extensions for the Dart SDK in the [`collections`](https://pub.dev/packages/collection) package. This would make sure the methods feel darty.

I understand your point. But to be honest, I don't think all this mutability and immutability is worth having a separated collection classes.

Don't take me wrong. I use your library on a huge project and I love it. But having to do all the transformation from Lists to KtLists (and worse, KtMutableList) is a real pain and caused me lots of debugging time, because one type is different from the other, so, serialization and deserialization is real problem.

Pehaps the best of both worlds would be a separared library called "kt_extensions" that would provide the awesome Kotlin collection functions to the Dart's collections, without worrying too much about the problems you pointed out.

**Comment by passsy** [comment]
For me, immutability by default is absolutely worth using another library with other collection classes. You can read up my argumentation [here](https://medium.com/flutter-community/kt-dart-better-collections-for-your-flutter-business-logic-41886ab7883#e9b4).

Can you create a new issue where you have problems converting between dart collections and kt collections? It should be relatively easy, especially with the new extensions in this PR.

```dart
// New: Converting dart collections to ktdart collections
final KtList<String> = ["hey"].kt;
final KtSet<String> = {"hey"}.kt;
final KtMap<String, int> = {"hey": 1}.kt;

// Converting ktdart collections to dart collections
final List<String> = listOf("hey").asList();
final Set<String> = setOf("hey").asSet();
final Map<String> = mapFrom({"hey": 1}).asMap();
```

**Comment by shinayser** [comment]
> For me, immutability by default is absolutely worth using another library with other collection classes. You can read up my argumentation [here](https://medium.com/flutter-community/kt-dart-better-collections-for-your-flutter-business-logic-41886ab7883#e9b4).
> 
> Can you create a new issue where you have problems converting between dart collections and kt collections? It should be relatively easy, especially with the new extensions in this PR.
> 
> ```dart
> // New: Converting dart collections to ktdart collections
> final KtList<String> = ["hey"].kt;
> final KtSet<String> = {"hey"}.kt;
> final KtMap<String, int> = {"hey": 1}.kt;
> 
> // Converting ktdart collections to dart collections
> final List<String> = listOf("hey").asList();
> final Set<String> = setOf("hey").asSet();
> final Map<String> = mapFrom({"hey": 1}).asMap();
> ```

The problems I had is because my code was expecting the default types, and when I introduced the KtDart types, eveything broke. I had to rewrite all the serialization code to make that work.
This was a huge refactor since the project is really big.
With the new  extensions, things will get better since just a ".kt" will transform the type, but still a different type.

Another advantage of a new library with extensions for the dart default types is that it will isntant work with any project already in production, no need for refactor.

**Pull request merged**
